"""
test_jellyfin_compat.py — Jellyfin Docker 相容 smoke test

Wave 1 gate for feature/72 external-manager-compat.

Spins up jellyfin/jellyfin:10.10.7 in a throwaway container, creates an
NFO-only movie library, triggers a scan, and asserts:
  - F3 NFO fields (uniqueid/sorttitle/country/plot/images) map through the REST API
  - F2 cd1/cd2 stacking: two video files collapse into ONE movie item with PartCount==2
  - F2 cd2-cover-kept: cd2 with its own images (no cd2.nfo) still stacks correctly

Skip guards: no Docker, no ffmpeg → skip entire module (not fail).
NFO is generated by the real core.organizer.generate_nfo() (T3 implementation).
"""
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

import pytest

# ── Module-level skip guards ───────────────────────────────────────────────────

def _docker_available() -> bool:
    try:
        result = subprocess.run(
            ["docker", "info"],
            capture_output=True,
            timeout=10,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _ffmpeg_available() -> bool:
    return shutil.which("ffmpeg") is not None


if not _docker_available():
    pytest.skip("Docker not available", allow_module_level=True)

if not _ffmpeg_available():
    pytest.skip("ffmpeg not available", allow_module_level=True)

# ── Imports that need Docker/ffmpeg guard above ───────────────────────────────

import requests  # noqa: E402  (after skip guards)

from core.organizer import generate_nfo  # noqa: E402

# ── Constants ─────────────────────────────────────────────────────────────────

JELLYFIN_IMAGE = "jellyfin/jellyfin:10.10.7"
CONTAINER_NAME = "oa-jf-smoke"
HOST_PORT = 8097
BASE_URL = f"http://localhost:{HOST_PORT}"

# ── Fixture helpers (inline, no import from poc/) ────────────────────────────


def make_tiny_mp4(path: Path) -> None:
    """Create a 1-second minimal mp4 using ffmpeg lavfi."""
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi",
            "-i", "color=black:size=32x32:rate=1",
            "-t", "1",
            "-c:v", "libx264",
            str(path),
        ],
        check=True,
        capture_output=True,
    )


def make_solid_jpg(path: Path, color=(20, 20, 20)) -> None:
    """Create a tiny solid-colour JPEG using Pillow."""
    try:
        from PIL import Image
    except ImportError:
        pytest.skip("Pillow not available — cannot generate fixture images")
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", (120, 80), color=color).save(str(path))


# ── Session-scoped fixture ────────────────────────────────────────────────────

@pytest.fixture(scope="session")
def jellyfin_env(tmp_path_factory):
    """
    Spin up a throwaway Jellyfin container with three fixture movie trees,
    run the setup wizard, create an NFO-only library, scan, and poll until
    items appear. Yields (base_url, headers, user_id). Tears down on exit.

    All infrastructure failures → pytest.skip (not pytest.fail).
    """
    media_root: Path = tmp_path_factory.mktemp("oa-jf-media")

    # ── Named volumes (avoids host-permission issues — pit ③) ──────────────
    suffix = uuid.uuid4().hex[:8]
    vol_config = f"oa-jf-smoke-config-{suffix}"
    vol_cache = f"oa-jf-smoke-cache-{suffix}"

    # ── Build fixture trees ────────────────────────────────────────────────

    # 1. single/ABC-123/ ──────────────────────────────────────────────
    # generate_nfo(output_path=...) writes directly to that path.
    # Pass the .nfo path; stem matches mp4/image stems so image refs are correct.
    single_dir = media_root / "single" / "ABC-123"
    single_dir.mkdir(parents=True, exist_ok=True)
    mp4_abc = single_dir / "ABC-123.mp4"
    nfo_abc = single_dir / "ABC-123.nfo"
    make_tiny_mp4(mp4_abc)
    make_solid_jpg(single_dir / "ABC-123.jpg", color=(40, 80, 160))
    make_solid_jpg(single_dir / "ABC-123-poster.jpg", color=(160, 40, 80))
    make_solid_jpg(single_dir / "ABC-123-fanart.jpg", color=(40, 160, 80))
    ok = generate_nfo(
        number="ABC-123",
        title="POC Sample Title",
        external_manager="jellyfin",
        has_poster=True,
        has_fanart=True,
        output_path=str(nfo_abc),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15",
        maker="POC Studio",
        actors=["POC Actress"],
        tags=["POC-Tag"],
    )
    if not ok:
        pytest.skip("generate_nfo failed for ABC-123")

    # 2. stack/DEF-456/ ───────────────────────────────────────────────
    stack_dir = media_root / "stack" / "DEF-456"
    stack_dir.mkdir(parents=True, exist_ok=True)
    mp4_cd1 = stack_dir / "DEF-456-cd1.mp4"
    mp4_cd2 = stack_dir / "DEF-456-cd2.mp4"
    make_tiny_mp4(mp4_cd1)
    make_tiny_mp4(mp4_cd2)
    make_solid_jpg(stack_dir / "DEF-456-cd1.jpg", color=(40, 80, 160))
    make_solid_jpg(stack_dir / "DEF-456-cd1-poster.jpg", color=(160, 40, 80))
    make_solid_jpg(stack_dir / "DEF-456-cd1-fanart.jpg", color=(40, 160, 80))
    nfo_def = stack_dir / "DEF-456-cd1.nfo"
    ok = generate_nfo(
        number="DEF-456",
        title="POC Stack Title",
        external_manager="jellyfin",
        has_poster=True,
        has_fanart=True,
        output_path=str(nfo_def),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15",
        maker="POC Studio",
    )
    if not ok:
        pytest.skip("generate_nfo failed for DEF-456")
    # cd2: NO nfo, NO extra images

    # 3. cd2cover/MIX-789/ ────────────────────────────────────────────
    cd2cover_dir = media_root / "cd2cover" / "MIX-789"
    cd2cover_dir.mkdir(parents=True, exist_ok=True)
    mp4_mix_cd1 = cd2cover_dir / "MIX-789-cd1.mp4"
    mp4_mix_cd2 = cd2cover_dir / "MIX-789-cd2.mp4"
    make_tiny_mp4(mp4_mix_cd1)
    make_tiny_mp4(mp4_mix_cd2)
    # cd1: full image set + nfo
    make_solid_jpg(cd2cover_dir / "MIX-789-cd1.jpg", color=(40, 80, 160))
    make_solid_jpg(cd2cover_dir / "MIX-789-cd1-poster.jpg", color=(160, 40, 80))
    make_solid_jpg(cd2cover_dir / "MIX-789-cd1-fanart.jpg", color=(40, 160, 80))
    nfo_mix = cd2cover_dir / "MIX-789-cd1.nfo"
    ok = generate_nfo(
        number="MIX-789",
        title="POC CD2Cover Title",
        external_manager="jellyfin",
        has_poster=True,
        has_fanart=True,
        output_path=str(nfo_mix),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15",
        maker="POC Studio",
    )
    if not ok:
        pytest.skip("generate_nfo failed for MIX-789")
    # cd2: own images, NO cd2.nfo (probe_cd2cover pattern)
    make_solid_jpg(cd2cover_dir / "MIX-789-cd2.jpg", color=(90, 90, 90))
    make_solid_jpg(cd2cover_dir / "MIX-789-cd2-poster.jpg", color=(90, 90, 90))
    make_solid_jpg(cd2cover_dir / "MIX-789-cd2-fanart.jpg", color=(90, 90, 90))

    # 4. newlayout/GHI-012/ ─────────────────────────────────────────────
    # TASK-112b-T7（DoD-8／AC9）：112 之後 OpenAver 自己新產生的片，正典封面
    # 直接落在 `-fanart.jpg`，磁碟上**沒有**獨立的同名 `.jpg`——只有
    # `-poster.jpg` + `-fanart.jpg` 兩張衍生圖。舊三棵樹（single/stack/
    # cd2cover）擺的「同名 + poster + fanart」三件套是**外部既有庫**的合法
    # 佈局（AC9 靠它），本樹補上 112 之後新產生片的佈局，兩者都要能在
    # Jellyfin 正常顯示封面/縮圖，缺一不可，**不刪除舊三棵樹**。
    newlayout_dir = media_root / "newlayout" / "GHI-012"
    newlayout_dir.mkdir(parents=True, exist_ok=True)
    mp4_ghi = newlayout_dir / "GHI-012.mp4"
    nfo_ghi = newlayout_dir / "GHI-012.nfo"
    make_tiny_mp4(mp4_ghi)
    make_solid_jpg(newlayout_dir / "GHI-012-poster.jpg", color=(160, 80, 40))
    make_solid_jpg(newlayout_dir / "GHI-012-fanart.jpg", color=(80, 160, 40))
    # 刻意不擺 GHI-012.jpg（裸 stem 同名封面）——這正是本樹要覆蓋的新佈局。
    ok = generate_nfo(
        number="GHI-012",
        title="POC NewLayout Title",
        external_manager="jellyfin",
        has_poster=True,
        has_fanart=True,
        output_path=str(nfo_ghi),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15",
        maker="POC Studio",
    )
    if not ok:
        pytest.skip("generate_nfo failed for GHI-012")

    # 5. bothnfo/JKL-345/ ────────────────────────────────────────────
    # AC-9 永久回歸守衛：cd1／cd2 各自完整（.mp4 + .nfo + 同名圖 + poster + fanart），
    # 兩份 NFO metadata 相同——這是 cd2 也寫 NFO 後 OpenAver 會產出的形狀。
    # probe-jellyfin-bothnfo.md 已用同一 harness 驗過：Jellyfin 仍收成 1 item、
    # PartCount=2（cd2 的 NFO/圖被忽略，不是被當第二部片）。
    bothnfo_dir = media_root / "bothnfo" / "JKL-345"
    bothnfo_dir.mkdir(parents=True, exist_ok=True)
    mp4_jkl_cd1 = bothnfo_dir / "JKL-345-cd1.mp4"
    mp4_jkl_cd2 = bothnfo_dir / "JKL-345-cd2.mp4"
    make_tiny_mp4(mp4_jkl_cd1)
    make_tiny_mp4(mp4_jkl_cd2)
    make_solid_jpg(bothnfo_dir / "JKL-345-cd1.jpg", color=(40, 80, 160))
    make_solid_jpg(bothnfo_dir / "JKL-345-cd1-poster.jpg", color=(160, 40, 80))
    make_solid_jpg(bothnfo_dir / "JKL-345-cd1-fanart.jpg", color=(40, 160, 80))
    nfo_jkl_cd1 = bothnfo_dir / "JKL-345-cd1.nfo"
    ok = generate_nfo(
        number="JKL-345", title="POC BothNfo Title", external_manager="jellyfin",
        has_poster=True, has_fanart=True, output_path=str(nfo_jkl_cd1),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15", maker="POC Studio",
    )
    if not ok:
        pytest.skip("generate_nfo failed for JKL-345 cd1")
    # cd2：自己的完整 NFO + 三張圖（metadata 與 cd1 相同）——這是本樹要驗的形狀
    make_solid_jpg(bothnfo_dir / "JKL-345-cd2.jpg", color=(40, 80, 160))
    make_solid_jpg(bothnfo_dir / "JKL-345-cd2-poster.jpg", color=(160, 40, 80))
    make_solid_jpg(bothnfo_dir / "JKL-345-cd2-fanart.jpg", color=(40, 160, 80))
    nfo_jkl_cd2 = bothnfo_dir / "JKL-345-cd2.nfo"
    ok = generate_nfo(
        number="JKL-345", title="POC BothNfo Title", external_manager="jellyfin",
        has_poster=True, has_fanart=True, output_path=str(nfo_jkl_cd2),
        summary="POC plot summary for harness assertion.",
        date="2024-01-15", maker="POC Studio",
    )
    if not ok:
        pytest.skip("generate_nfo failed for JKL-345 cd2")

    # ── Docker lifecycle ───────────────────────────────────────────────────

    # Clean up any leftover container/volumes from a previous run
    subprocess.run(["docker", "rm", "-f", CONTAINER_NAME], capture_output=True)
    subprocess.run(
        ["docker", "volume", "rm", vol_config, vol_cache],
        capture_output=True,
    )

    try:
        # Pull image
        pull = subprocess.run(
            ["docker", "pull", JELLYFIN_IMAGE],
            capture_output=True,
        )
        if pull.returncode != 0:
            pytest.skip(f"docker pull {JELLYFIN_IMAGE} failed: {pull.stderr.decode()[:200]}")

        # Start container
        run = subprocess.run(
            [
                "docker", "run", "-d",
                "--name", CONTAINER_NAME,
                "-p", f"{HOST_PORT}:8096",
                "-v", f"{vol_config}:/config",
                "-v", f"{vol_cache}:/cache",
                "-v", f"{str(media_root)}:/media:ro",
                "--restart", "no",
                JELLYFIN_IMAGE,
            ],
            capture_output=True,
        )
        if run.returncode != 0:
            pytest.skip(f"docker run failed: {run.stderr.decode()[:200]}")

        # ── Wait for Jellyfin to be ready (/System/Info/Public → 200) ──────
        deadline = time.time() + 120
        while time.time() < deadline:
            try:
                r = requests.get(f"{BASE_URL}/System/Info/Public", timeout=3)
                if r.status_code == 200:
                    break
            except Exception:
                pass
            time.sleep(3)
        else:
            pytest.skip("Jellyfin did not start in time (120s)")

        # ── Setup wizard (5 steps) ──────────────────────────────────────────
        requests.post(
            f"{BASE_URL}/Startup/Configuration",
            json={
                "UICulture": "en-US",
                "MetadataCountryCode": "JP",
                "PreferredMetadataLanguage": "ja",
            },
            timeout=10,
        )
        # GET /Startup/User first (Jellyfin expects it)
        requests.get(f"{BASE_URL}/Startup/User", timeout=10)
        requests.post(
            f"{BASE_URL}/Startup/User",
            json={"Name": "oa_test", "Password": "oa_test_pw"},
            timeout=10,
        )
        requests.post(
            f"{BASE_URL}/Startup/RemoteAccess",
            json={"EnableRemoteAccess": True, "EnableAutomaticPortMapping": False},
            timeout=10,
        )
        requests.post(f"{BASE_URL}/Startup/Complete", timeout=10)
        time.sleep(2)

        # ── Authenticate ────────────────────────────────────────────────────
        device_id = f"oa-smoke-{uuid.uuid4().hex[:8]}"
        emby_auth_base = (
            f'MediaBrowser Client="OA-Smoke",Device="pytest",'
            f'DeviceId="{device_id}",Version="1.0"'
        )
        auth_resp = requests.post(
            f"{BASE_URL}/Users/AuthenticateByName",
            json={"Username": "oa_test", "Pw": "oa_test_pw"},
            headers={"X-Emby-Authorization": emby_auth_base},
            timeout=10,
        )
        if auth_resp.status_code != 200:
            pytest.skip(f"Auth failed: {auth_resp.status_code} {auth_resp.text[:200]}")
        auth_data = auth_resp.json()
        token = auth_data["AccessToken"]
        user_id = auth_data["User"]["Id"]
        headers = {
            "X-Emby-Authorization": (
                f'{emby_auth_base},Token="{token}"'
            )
        }

        # ── Create NFO-only movie library ───────────────────────────────────
        # PathInfos in body is required — query param `paths` alone is unreliable (pit ①)
        lib_resp = requests.post(
            f"{BASE_URL}/Library/VirtualFolders",
            params={
                "collectionType": "movies",
                "name": "OA-Smoke-Movies",
                "refreshLibrary": "false",
            },
            headers=headers,
            json={
                "LibraryOptions": {
                    "EnableRealtimeMonitor": False,
                    "EnableInternetProviders": False,
                    "SaveLocalMetadata": False,
                    "MetadataSavers": [],
                    "LocalMetadataReaderOrder": ["Nfo"],
                    "PathInfos": [{"Path": "/media"}],
                    "TypeOptions": [
                        {
                            "Type": "Movie",
                            "MetadataFetchers": [],
                            "MetadataFetcherOrder": [],
                            "ImageFetchers": [],
                            "ImageFetcherOrder": [],
                        }
                    ],
                    "EnableChapterImageExtraction": False,
                }
            },
            timeout=30,
        )

        # Verify library was created with valid Locations (pit ①)
        vf_resp = requests.get(f"{BASE_URL}/Library/VirtualFolders", headers=headers, timeout=10)
        folders = vf_resp.json()
        oa_folder = next(
            (f for f in folders if f.get("Name") == "OA-Smoke-Movies"), None
        )
        if oa_folder is None:
            pytest.skip("Library creation failed — OA-Smoke-Movies not found")
        locations = oa_folder.get("Locations", [])
        if not locations:
            pytest.skip(
                "Library has no Locations — possible Jellyfin version mismatch (pit ①)"
            )

        # ── Trigger scan and wait (pit ②) ───────────────────────────────────
        # Find the scan scheduled task
        tasks_resp = requests.get(f"{BASE_URL}/ScheduledTasks", headers=headers, timeout=10)
        tasks = tasks_resp.json()
        scan_task = next(
            (
                t
                for t in tasks
                if ("Scan" in t.get("Name", "") and "Librar" in t.get("Name", ""))
                or t.get("Key") == "RefreshLibrary"
            ),
            None,
        )
        if scan_task:
            tid = scan_task["Id"]
            requests.post(
                f"{BASE_URL}/ScheduledTasks/Running/{tid}", headers=headers, timeout=10
            )
            # Wait for scan to START (leave Idle) before waiting for it to finish
            for _ in range(15):
                state_resp = requests.get(
                    f"{BASE_URL}/ScheduledTasks/{tid}", headers=headers, timeout=10
                )
                if state_resp.json().get("State") == "Running":
                    break
                time.sleep(0.5)
            # Now wait for scan to return to Idle
            deadline = time.time() + 300
            while time.time() < deadline:
                state_resp = requests.get(
                    f"{BASE_URL}/ScheduledTasks/{tid}", headers=headers, timeout=10
                )
                if state_resp.json().get("State") == "Idle":
                    time.sleep(4)  # let items commit to DB
                    break
                time.sleep(2)
        else:
            # Fallback: trigger generic refresh and wait
            requests.post(f"{BASE_URL}/Library/Refresh", headers=headers, timeout=10)
            time.sleep(10)

        # ── Poll until items appear (pit ②) ─────────────────────────────────
        deadline2 = time.time() + 60
        item_count = 0
        while time.time() < deadline2:
            items_resp = requests.get(
                f"{BASE_URL}/Users/{user_id}/Items",
                params={"IncludeItemTypes": "Movie", "Recursive": "true"},
                headers=headers,
                timeout=15,
            )
            item_count = items_resp.json().get("TotalRecordCount", 0)
            if item_count > 0:
                break
            time.sleep(5)

        if item_count == 0:
            pytest.skip(
                "No items scanned — Jellyfin may not have parsed the NFO files"
            )

        yield (BASE_URL, headers, user_id)

    finally:
        subprocess.run(["docker", "rm", "-f", CONTAINER_NAME], capture_output=True)
        subprocess.run(
            ["docker", "volume", "rm", vol_config, vol_cache], capture_output=True
        )


# ── Test class ────────────────────────────────────────────────────────────────


@pytest.mark.smoke
class TestJellyfinCompat:
    """F2/F3 compatibility assertions against real Jellyfin REST API."""

    def test_f3_nfo_fields(self, jellyfin_env):
        """
        ABC-123 single movie: F3 NFO fields (uniqueid/sorttitle/country/plot/images)
        must map correctly through the Jellyfin REST API.
        """
        base_url, headers, user_id = jellyfin_env
        resp = requests.get(
            f"{base_url}/Users/{user_id}/Items",
            params={
                "IncludeItemTypes": "Movie",
                "Recursive": "true",
                "Fields": "Overview,ProviderIds,SortName,ProductionLocations",
                "EnableImages": "true",
            },
            headers=headers,
            timeout=15,
        )
        items = resp.json()["Items"]

        # Locate ABC-123 by ProviderIds or name
        abc = next(
            (
                i
                for i in items
                if i.get("ProviderIds", {}).get("num") == "ABC-123"
            ),
            None,
        )
        if abc is None:
            abc = next(
                (
                    i
                    for i in items
                    if "poc sample" in i.get("Name", "").lower()
                    or "ABC" in i.get("Name", "").upper()
                ),
                None,
            )
        assert abc is not None, (
            f"ABC-123 not found in items: {[i.get('Name') for i in items]}"
        )

        assert abc.get("ProviderIds", {}).get("num") == "ABC-123", (
            f"ProviderIds.num mismatch: {abc.get('ProviderIds')}"
        )
        assert "Japan" in (abc.get("ProductionLocations") or []), (
            f"Japan not in ProductionLocations: {abc.get('ProductionLocations')}"
        )
        sort_name = (abc.get("SortName") or "").lower()
        assert "poc sample title" in sort_name or "poc sample" in sort_name, (
            f"title not in SortName: {sort_name!r}"
        )
        assert "POC plot" in (abc.get("Overview") or ""), (
            f"Overview mismatch: {abc.get('Overview')!r}"
        )
        assert "Primary" in (abc.get("ImageTags") or {}), (
            f"No Primary image: {abc.get('ImageTags')}"
        )
        assert len(abc.get("BackdropImageTags") or []) > 0, (
            f"No BackdropImageTags: {abc.get('BackdropImageTags')}"
        )

    def test_f2_stacking_cd1cd2(self, jellyfin_env):
        """
        DEF-456 cd1+cd2: exactly ONE movie item must appear, with PartCount==2
        or len(MediaSources)==2. Stacking works with NFO+images only on cd1 stem.
        """
        base_url, headers, user_id = jellyfin_env
        resp = requests.get(
            f"{base_url}/Users/{user_id}/Items",
            params={
                "IncludeItemTypes": "Movie",
                "Recursive": "true",
                "Fields": "ProviderIds,PartCount",
            },
            headers=headers,
            timeout=15,
        )
        items = resp.json()["Items"]

        def_ = next(
            (
                i
                for i in items
                if i.get("ProviderIds", {}).get("num") == "DEF-456"
            ),
            None,
        )
        if def_ is None:
            def_ = next(
                (
                    i
                    for i in items
                    if "DEF" in i.get("Name", "").upper()
                    or "poc stack" in i.get("Name", "").lower()
                ),
                None,
            )
        assert def_ is not None, (
            f"DEF-456 not found; items: {[i.get('Name') for i in items]}"
        )

        # Exactly ONE item for DEF-456
        def_items = [
            i
            for i in items
            if i.get("ProviderIds", {}).get("num") == "DEF-456"
            or "DEF" in i.get("Name", "").upper()
        ]
        assert len(def_items) == 1, (
            f"Expected 1 stacked item for DEF-456, got {len(def_items)}: "
            f"{[i.get('Name') for i in def_items]}"
        )

        # PartCount==2 or MediaSources has 2 entries
        item_id = def_["Id"]
        detail = requests.get(
            f"{base_url}/Items/{item_id}",
            params={"Fields": "MediaSources"},
            headers=headers,
            timeout=15,
        ).json()
        part_count = def_.get("PartCount", 0) or detail.get("PartCount", 0)
        media_sources = detail.get("MediaSources", [])
        assert part_count == 2 or len(media_sources) == 2, (
            f"Expected 2 parts/sources for DEF-456, "
            f"got PartCount={part_count}, MediaSources={len(media_sources)}"
        )

    def test_f2_cd2_cover_kept_no_nfo(self, jellyfin_env):
        """
        MIX-789: cd2 has its own cover images but NO cd2.nfo.
        Jellyfin must still stack both into ONE item with PartCount==2
        (probe_cd2cover verified: cd2 cover does not break stacking).
        """
        base_url, headers, user_id = jellyfin_env
        resp = requests.get(
            f"{base_url}/Users/{user_id}/Items",
            params={
                "IncludeItemTypes": "Movie",
                "Recursive": "true",
                "Fields": "ProviderIds,PartCount",
            },
            headers=headers,
            timeout=15,
        )
        items = resp.json()["Items"]

        mix = next(
            (
                i
                for i in items
                if i.get("ProviderIds", {}).get("num") == "MIX-789"
            ),
            None,
        )
        if mix is None:
            mix = next(
                (
                    i
                    for i in items
                    if "MIX" in i.get("Name", "").upper()
                    or "poc cd2cover" in i.get("Name", "").lower()
                ),
                None,
            )
        assert mix is not None, (
            f"MIX-789 not found; items: {[i.get('Name') for i in items]}"
        )

        mix_items = [
            i
            for i in items
            if i.get("ProviderIds", {}).get("num") == "MIX-789"
            or "MIX" in i.get("Name", "").upper()
        ]
        assert len(mix_items) == 1, (
            f"Expected 1 stacked item for MIX-789, got {len(mix_items)}: "
            f"{[i.get('Name') for i in mix_items]}"
        )

        # Resolve PartCount (list endpoint may not populate it fully)
        part_count = mix.get("PartCount", 0)
        if part_count == 0:
            item_id = mix["Id"]
            detail = requests.get(
                f"{base_url}/Items/{item_id}",
                params={"Fields": "MediaSources"},
                headers=headers,
                timeout=15,
            ).json()
            part_count = detail.get("PartCount", 0)
            if part_count == 0:
                part_count = len(detail.get("MediaSources", []))
        assert part_count == 2, (
            f"Expected PartCount==2 for MIX-789, got {part_count}"
        )

    def test_f2_bothnfo_cd1cd2_each_own_nfo(self, jellyfin_env):
        """
        JKL-345: cd1／cd2 各自有完整 NFO + 圖（AC-9，cd2 也寫 NFO 後的新常態）。
        Jellyfin 仍必須收成 ONE item，PartCount==2——這是永久回歸守衛，
        若之後有人讓 cd2 的 NFO 破壞 stacking（例如誤把 cd2 的 title 寫進單獨
        item），這支會紅。
        """
        base_url, headers, user_id = jellyfin_env
        resp = requests.get(
            f"{base_url}/Users/{user_id}/Items",
            params={"IncludeItemTypes": "Movie", "Recursive": "true",
                    "Fields": "ProviderIds,PartCount"},
            headers=headers, timeout=15,
        )
        items = resp.json()["Items"]
        jkl = next((i for i in items if i.get("ProviderIds", {}).get("num") == "JKL-345"), None)
        if jkl is None:
            jkl = next((i for i in items if "JKL" in i.get("Name", "").upper()
                        or "poc bothnfo" in i.get("Name", "").lower()), None)
        assert jkl is not None, f"JKL-345 not found; items: {[i.get('Name') for i in items]}"

        jkl_items = [i for i in items if i.get("ProviderIds", {}).get("num") == "JKL-345"
                     or "JKL" in i.get("Name", "").upper()]
        assert len(jkl_items) == 1, (
            f"Expected 1 stacked item for JKL-345, got {len(jkl_items)}: "
            f"{[i.get('Name') for i in jkl_items]}"
        )

        part_count = jkl.get("PartCount", 0)
        if part_count == 0:
            item_id = jkl["Id"]
            detail = requests.get(f"{base_url}/Items/{item_id}",
                                   params={"Fields": "MediaSources"},
                                   headers=headers, timeout=15).json()
            part_count = detail.get("PartCount", 0) or len(detail.get("MediaSources", []))
        assert part_count == 2, f"Expected PartCount==2 for JKL-345, got {part_count}"

    def test_f_newlayout_no_bare_stem_cover_shows_images(self, jellyfin_env):
        """
        TASK-112b-T7（DoD-8／AC9）：GHI-012 只有 `-poster.jpg`/`-fanart.jpg`，
        磁碟上**沒有**同名 `.jpg`（112 之後 OpenAver 自己新產生片的佈局）。
        Jellyfin 仍必須正常吐出封面（Primary）與縮圖（BackdropImageTags），
        不得破圖或空白——這是 AC9「新佈局片在媒體伺服器正常顯示」的 smoke 驗證。
        """
        base_url, headers, user_id = jellyfin_env
        resp = requests.get(
            f"{base_url}/Users/{user_id}/Items",
            params={
                "IncludeItemTypes": "Movie",
                "Recursive": "true",
                "Fields": "ProviderIds",
                "EnableImages": "true",
            },
            headers=headers,
            timeout=15,
        )
        items = resp.json()["Items"]

        ghi = next(
            (
                i
                for i in items
                if i.get("ProviderIds", {}).get("num") == "GHI-012"
            ),
            None,
        )
        if ghi is None:
            ghi = next(
                (
                    i
                    for i in items
                    if "GHI" in i.get("Name", "").upper()
                    or "poc newlayout" in i.get("Name", "").lower()
                ),
                None,
            )
        assert ghi is not None, (
            f"GHI-012 not found in items: {[i.get('Name') for i in items]}"
        )

        assert ghi.get("ProviderIds", {}).get("num") == "GHI-012", (
            f"ProviderIds.num mismatch: {ghi.get('ProviderIds')}"
        )
        assert "Primary" in (ghi.get("ImageTags") or {}), (
            f"No Primary image despite no bare-stem cover file: {ghi.get('ImageTags')}"
        )
        assert len(ghi.get("BackdropImageTags") or []) > 0, (
            f"No BackdropImageTags despite no bare-stem cover file: "
            f"{ghi.get('BackdropImageTags')}"
        )
